name: Update Database

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 12 hours

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # or your desired Python version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt with the necessary packages

    - name: Run script
      run: python3 update_db.py
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
